### ISSUE TITLE
お知らせ機能

### ISSUE THREAD

**Issue by banira0428** [oucrc/web#25]
目的：「新型感染症の影響で現在部室への立ち入りを制限しています」のような、一時的なお知らせをおいておく場所が欲しい

具体的内容：新たに Notice コンポーネントを作成し、Top と Contents の間に挟み込む． Notice コンポーネント内のデザインについてはお任せします （UIkit を活用してくれるとありがたい）

変更箇所：新規にファイルを作成してください（他の`.vue`ファイルを参考にしながら）

**Comment by AAAR-Salmon** [comment]
こちら取り組んでみます

**Comment by oucrc** [comment]
完了したのでクローズします
