### ISSUE TITLE
スライドショーのサムネイル用の画像を作成

### ISSUE THREAD

**Issue by banira0428** [oucrc/web#26]
目的：ページ上部のスライドショーのサムネイル画像にオリジナルの画像を使用しており、64px の幅の部分に750pxの画像を表示しているためパフォーマンス的によろしくない

作業内容：横幅の小さい画像を別途用意し、Topコンポーネントの内容を差し替える

変更箇所：`Top.vue`の20行目付近

**Comment by Wansuko-cmd** [comment]
やってみます

**Comment by banira0428** [comment]
解決したのでクローズ
